- name: Copy and run Weather Report
  hosts: all
  become: yes

  tasks:
    - name: Copy the script
      copy:
        src: "{{ playbook_dir }}/Final_Report_Capstone_Project.csv"
        dest: /tmp/Final_Report_Capstone_Project.csv
        mode: '0755'
