- name: Copy and run block IP script
  hosts: all
  become: yes

  tasks:
    - name: Copy the script
      copy:
        src: "{{ playbook_dir }}/block_ip.sh"
        dest: /tmp/block_ip.sh
        mode: '0755'

    - name: Copy the block list file
      copy:
        src: "{{ playbook_dir }}/TOR_IP_block_list.txt"
        dest: /tmp/ip_block_list.txt
        mode: '0644'

    - name: Execute the script
      shell: /tmp/block_ip.sh
